spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:~/cafeKioskApplication;DB_CLOSE_DELAY=-1 # localhost:8080/h2-console? ??
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none # ddl auto ??? ?? ??????? none??, ??? ???? ?? ????? ?? ??.

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true # ?? ????? ???. ? ???? ?? ? ? ??
    defer-datasource-initialization: true # ?????? 2.5?? ??. ?????? ??? ?? data.sql ??

  h2:
    console:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never # ??? ??? ?? ???? ?? ??? sql.init.mode: never
